# 该workflow的名称，可以随意填写
name: Publish And Deploy

# workflow的触发事件，这里代表release分支的push事件触发
on:
  push:
    branches: [develop]

# 任务
jobs:
  build:
    # 运行所需要的环境
    runs-on: ubuntu-latest

    steps:
      # 检查公共的三方js文件是否可用
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://web.90c.vip"
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # 依赖缓存
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # 下载依赖
      - name: install
        run: |
          npm install
        env:
          CI: true
      # Run Lighthouse
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: 'https://web.90c.vip'
          # ... all your other inputs
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          # 最低Accessibility分数
          minAccessibilityScore: "70"
          # 性能最低分
          minBestPracticesScore: "30"
          minPerformanceScore: "30"
          minProgressiveWebAppScore: "30"
          minSeoScore: "30"
      # 构建
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      # 生成压缩包
      - run: tar -zcvf release.tgz .nuxt  nuxt.config.ts package.json  pm2.config.json postbuild.ts config tsconfig.json yarn.lock

      # 上传文件
      - name: Upload
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: '-avz --delete'
          SOURCE: 'release.tgz'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}

      # 部署
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          # 远程服务器端口号
          port: ${{ secrets.PORT }}
          # 命令超时配置 默认10m
          command_timeout: 20m
          # 运行在远程服务器的命令
          # 1. 进入项目目录
          # 2. 下载发布包
          # 3. 解压缩发布包
          # 4. 安装生产环境依赖
          # 5. pm2运行配置文件
          script: |
            cd /www/wwwroot/web.90c.vip
            tar zxvf release.tgz
            npm install --production
            pm2 reload pm2.config.json
      # 微信通知
      - name: Wechat Notification
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.DEV_WECHAT_WEBHOOK }}
        with:
          msgtype: markdown
          content: "来画平台<font color=\"warning\">v5.2.3</font>更新了，快来试试看吧～。\n
          > \n
          ##### 修改内容：\n
          > <font color=\"info\">${{ github.event.head_commit.message }}</font> \n
          ##### 修改分支:\n
          > <font color=\"info\">${{ github.event.ref }}</font> \n
          ##### 修改时间:\n
          > <font color=\"info\">${{ github.event.head_commit.timestamp }}</font> \n
          ##### 修改人:\n
          > <font color=\"info\">${{ github.event.head_commit.committer.name }}</font>\n
          详情请点击:[来画平台](https://web.90c.vip)\n"
          mentioned_list: ['@all']
